---
- hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]

  tasks:
    - import_tasks: tasks/vs-code.yml
      when: configure_vscode
      tags: ["vscode"]

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]
